FROM python:3.5.2

RUN apt-get update
RUN apt-get install git

#RUN git clone --recursive -b sistemas https://github.com/bredondo/pitufos_project.git
RUN pip install -r requirements.txt

EXPOSE 8000

#WORKDIR /pitufos_project/backend

#ENTRYPOINT python insert.py
#ENTRYPOINT python main.py


